- hosts: Centos
  become: true
  remote_user: centos
  
  pre_tasks:
  - name: Install Wget
    yum: 
      name: wget
      state: present
  - name: Install Epel Release package
    yum: 
      name: epel-release
      state: present
  - name: Install dnf
    yum: 
      name: python2-dnf
      state: present
  - name: "Install Postgres Server"
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - postgresql
      - postgresql-server
  tasks:
  - name: "Find out if PostgreSQL is initialized"
    ansible.builtin.stat:
      path: "/var/lib/pgsql/data/pg_hba.conf"
    register: postgres_data

  - name: "Initialize PostgreSQL"
    shell: "postgresql-setup initdb"
    when: not postgres_data.stat.exists

  - name: "Start and enable services"
    service: "name={{ item }} state=started enabled=yes"
    with_items:
      - postgresql
