- hosts: ArmGraviton
  become: true

  pre_tasks:
    - name: "Install packages"
      dnf: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-server

    - name: "Install Python packages"
      yum: "name={{ item }}  state=present"
      with_items:
        - python3-psycopg2

  tasks:
  - name: Create a file
    file: 
      path=/home/ec2-user/ansible-file.txt 
      state=touch
  - name: "Find out if PostgreSQL is initialized"
    ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
    register: postgres_data
  - name: "Initialize PostgreSQL"
    shell: "postgresql-setup initdb"
    when: not postgres_data.stat.exists

  - name: "Start and enable services"
    service: "name={{ item }} state=started enabled=yes"
    with_items:
      - postgresql
