- hosts: Centos
  become: true
  vars:
    ansible_python_interpreter: /bin/python3
  remote_user: centos
  
  vars_files:
    - vars.yml
    
  tasks:
  - name: "Create app database"
    postgresql_db:
      state: present
      name: "{{ db_name }}"
    become: yes
    become_user: postgres
  - name: Ensure user has access to the new database
    postgresql_user: 
      db: "{{ db_name }}"
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      priv: ALL
      state: present
      role_attr_flags: LOGIN
    become: true
    become_user: postgres
  - name: "Allow md5 connection for the db user"
    postgresql_pg_hba:
      dest: "~/data/pg_hba.conf"
      contype: host
      databases: all
      method: md5
      users: "{{ db_user }}"
      create: true
    become: yes
    become_user: postgres
    notify: restart postgres

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted