- hosts: AmazonLinux
  become: true
  vars:
    ansible_python_interpreter: /bin/python3
    container_count: 1
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1
  
  tasks: 
  - name: install latest version of docker
    yum:
      name: docker
      state: latest
  - name: Copy file with owner and permission, using symbolic representation
    copy:
      src: ./docker-permission.sh
      dest: /tmp/docker-permission.sh
      owner: ec2-user
      group: ec2-user
      mode: u=rx,g=rx,o=rx
  - name: Check docker version
    shell: 
      "./docker-permission.sh"
    args:
      chdir: /tmp/
  - name: Install Docker Module for Python
    pip:
      name: docker
  - name: Pull default Docker image
    docker_image:
      name: "{{ default_container_image }}"
      source: pull
  - name: Create default containers
    docker_container:
      name: "{{ default_container_name }}{{ item }}"
      image: "{{ default_container_image }}"
      state: present
    with_sequence: count={{ container_count }}