- hosts: ubuntu-remote
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Install required system packages
    apt:
      pkg:
        - curl

  - name: Start and enable Docker daemon
    service:
      name: docker
      enabled: true
